spring:
  application:
    name: cryptowatch-two
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.cryptowatch: DEBUG
